spring.datasource.url=jdbc:postgresql://localhost:5432/garage_db
spring.datasource.username=postgres
spring.datasource.password=2122

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=tanmaybhosale703@gmail.com
spring.mail.password=1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true